Repository swaglive/docker-ckip-transformers, pull requests merged in 2023-01, with the labels that each got.

#1 Phase 1 - Add flask server
  .gitignore
  app.py
  poetry.lock
  pyproject.toml
Labels: feature, p2

#2 Phase 2 - Add dockerfile
  .dockerignore
  Dockerfile
  config/uwsgi.ini
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: feature, p2

#3 Phase 3 - Add docker-compose
  docker-compose.yaml
Labels: feature, p2

#8 Add cli `touch`
  Dockerfile
  app.py
Labels: optimization, p2

#10 Add healthz
  app.py
Labels: feature, p2

#12 Fix: `CKIP_DEVICE` should be integer
  app.py
Labels: bug, p2

#9 Add platform arm
  .github/workflows/docker.yaml
Labels: optimization, p3
